-- 1, 1
INSERT INTO CAP_BAC (LOAI_CAP_BAC, PHAN_TRAM_GIAM_GIA) 
VALUES 
('Normal', 0), 
('VIP Gold', 5), 
('VIP Diamond', 10);

-- 1000000, 1
INSERT INTO KHACH_HANG (MA_CAP_BAC, TENKH, EMAIL_KH, TONG_DIEM_TICH_LUY, MAT_KHAU) 
VALUES 
(1, N'Nguyễn Thị Ngọc Diệu', 'ntnd1@example.com', 0, 'mk123'),
(3, N'Lê Thị Phương Linh', 'ltpl2@example.com', 1609, 'mk123'),
(1, N'Phan Khải Đông', 'pkd3@example.com', 0, 'mk123'),
(2, N'Bùi Đăng Khoa', 'bdk4@example.com', 329, 'mk123'),
(1, N'Tống Thảo Nhi', 'ttn5@example.com', 67, 'mk123'),
(1, N'Nguyễn Thị Bích Phương', 'ntbp6@example.com', 0, 'mk123'),
(1, N'Trần Thị Lan Anh', 'ttla7@example.com', 0, 'mk123'),
(3, N'Nguyễn Như Ngọc', 'nnn8@example.com', 1654, 'mk123'),
(1, N'Nguyễn Phạm Mỹ Duyên', 'npmd9@example.com', 0, 'mk123'),
(1, N'Huỳnh Nguyễn Thùy Nhiên', 'hntn10@example.com', 49, 'mk123'),
(2, N'Nguyễn Quang Trường', 'nqt11@example.com', 765, 'mk123'),
(1, N'Hà Đức Trọng', 'hdt12@example.com', 0, 'mk123'),
(2, N'Trương Nguyên Thảo', 'tnt13@example.com', 652, 'mk123'),
(1, N'Nguyễn Tuyết Anh', 'nta14@example.com', 0, 'mk123'),
(1, N'Lê Thị Tú Loan', 'lttl15@example.com', 102, 'mk123'),
(1, N'Nguyễn Lê Tuấn Minh', 'nltm16@example.com', 0, 'mk123'),
(2, N'Võ Quang Duy', 'vqd17@example.com', 498, 'mk123'),
(1, N'Trương Nguyễn Thảo Nguyên', 'nttn18@example.com', 123, 'mk123'),
(1, N'Nguyễn Thị Thanh An', 'ntta19@example.com', 46, 'mk123'),
(2, N'Nguyễn Thị Hoài Linh', 'nthl20@example.com', 549, 'mk123'),
(3, N'Phan Quang Hiếu', 'pqh21@example.com', 1221, 'mk123'),
(1, N'Võ Như Quỳnh', 'vnq22@example.com', 0, 'mk123'),
(1, N'Huỳnh Thục Quyên', 'htq23@example.com', 53, 'mk123'),
(1, N'Lê Vũ Thảo Hiền', 'lvth24@example.com', 0, 'mk123'),
(1, N'Nguyễn Bá Quân', 'nbq25@example.com', 46, 'mk123'),
(1, N'Trần Vương Quỳnh Trân', 'tvqt26@example.com', 0, 'mk123'),
(1, N'Nguyễn Minh Thảo', 'nmt28@example.com', 0, 'mk123'),
(2, N'Nguyễn Trung Anh', 'nta29@example.com', 345, 'mk123'),
(1, N'Nguyễn Thị Kim Anh', 'ntka30@example.com', 0, 'mk123'),
(1, N'Huỳnh Thị Hồng Phấn', 'hthp31@example.com', 0, 'mk123'),
(1, N'Bùi Thị Kim Ngân', 'btkn32@example.com', 0, 'mk123'),
(1, N'Phan Tường Vy', 'ptv33@example.com', 0, 'mk123'),
(2, N'Nguyễn Thương Thương', 'ntt34@example.com', 323, 'mk123'),
(1, N'Lê Thị Minh Tuyền', 'ltmt35@example.com', 23, 'mk123');

-- 1000, 1
INSERT INTO NHA_PHAN_PHOI (TEN_NPP, SO_NHA_DUONG, PHUONG_XA, QUAN_TP, TP_TINH) 
VALUES 
('ROYAL CANIN', N'725 Nguyễn Tất Thành', N'3', N'2', N'HCM'),
('ZENITH', N'87 Bùi Thị Xuân', N'4', N'12', N'HCM'),
('ORIGI-7', N'35 Nguyễn Huệ', N'2', N'5', N'HCM'),
('INABA', N'123 CMT8', N'1', N'3', N'HCM'),
('VEGEBRAND', N'198 Nam Kỳ Khời Nghĩa', N'Bình Thuận', N'6', N'Đồng Nai'),
('WHISKAS', N'77 Lê Văn Lương', N'Phú Mỹ', N'9', N'HCM'),
('IRIS OHYAMA', N'225 Bùi Thị Xuân', N'4', N'1', N'HCM'),
('CIAO', N'49 Đồng Khởi', N'3', N'4', N'HCM'),
('JERHIGH', N'351 Nguyễn Văn Cừ', N'8', N'8', N'Hà Nội'),

('PETISMILE', N'167 Nguyễn Văn Quỳ', N'10', N'7', N'Hải Phòng'),
('BOBBYPET', N'29 Cống Quỳnh', N'Tân Phong', N'2', N'Lâm Đồng'),
('PAW', N'214 Hai Bà Trưng', N'7', N'9', N'Hà Nội'),
('AIMIGOU', N'987 Hoàng Hoa Thám', N'5', N'12', N'HCM'),
('AUPET', N'165 Đinh Tiên Hoàng', N'Tân Hưng', N'11', N'Vĩnh Long'),
('XINDING', N'324 Nguyễn Tất Thành', N'9', N'Bình Thạnh', N'HCM'),
('ELITE', N'595 Huỳnh Tấn Phát', N'3', N'Gò Vấp', N'Hà Nội'),

('DELE', N'64 Dương Bá Trạc', N'1', N'Thủ Đức', N'HCM'),
('AMBABY PET', N'214 Nguyễn Văn Linh', N'4', N'2', N'Ninh Thuận'),
('ANIME', N'265 Lý Thái Tổ', N'Ninh Thuận', N'4', N'Lâm Đồng'),
('LOFFE', N'43 3/2', N'5', N'8', N'Hải Phòng'),
('PETISMILE', N'538 Phan Bội Châu', N'12', N'9', N'HCM'),
('AUGUSTPET', N'28 Nguyễn Văn Trỗi', N'6', N'11', N'HCM'),

('BOBO', N'55 Đoàn Thị Điểm', N'1', N'1', N'Hà Nội'),
('JOYU', N'234 Hàm Nghi', N'7', N'2', N'HCM'),
('JOYCE & DOLLS', N'101 Nguyễn Lương Bằng', N'10', N'3', N'HCM'),
('PET SOFT', N'179 Phạm Văn Nghị', N'11', N'5', N'HCM'),
('TRIXIE', N'412 Tô Hiến Thành', N'Tân Quy', N'7', N'Đồng Nai'),
('BAYER', N'79 Sư Vạn Hạnh', N'8', N'12', N'HCM'),
('MAKAR', N'421 Lê Hồng Phong', N'11', N'10', N'HCM'),
('VET''S BEST', N'127 Tô Hiến Thành', N'9', N'8', N'HCM');


-- 200, 1
INSERT INTO CHI_NHANH (SDT_CN, SO_NHA_DUONG, PHUONG_XA, QUAN_TP, TP_TINH) 
VALUES 
('0987654321', N'112 Bùi Thị Xuân', N'5', N'1', N'HCM'),
('0987654322', N'231 Nguyễn Thị Thập', N'4', N'2', N'HCM'),
('0987654323', N'64 Nam Lỳ Khởi Nghĩa', N'7', N'3', N'HCM'),
('0987654324', N'256 Hoàng Hoa Thám', N'9', N'5', N'HCM'),
('0987654325', N'21 Nguyễn Văn Trỗi', N'8', N'7', N'HCM'),
('0987654326', N'572 An Dương Vương', N'6', N'10', N'HCM'),
('0987654327', N'375 Huỳnh Tấn Phát', N'2', N'Tân Phú', N'HCM'),
('0987654328', N'184 Võ Văn Kiệt', N'5', N'Bình Thạnh', N'HCM'),
('0987654329', N'83 Trần Hưng Đạo', N'1', N'Tân Bình', N'HCM');

-- 100000, 1
INSERT INTO VOUCHER (PHAN_TRAM_GIAM_GIA, GIAM_TOI_DA, TG_BAT_DAU, TG_KET_THUC, PHAN_LOAI) 
VALUES 
(5, 1000, '2022-06-20 00:00:00-07', '2022-07-01 00:00:00-07', N'A'),
(7, 100, '2022-06-25 00:00:00-07', '2022-07-01 00:00:00-07', N'B'),
(5, 500, '2022-06-30 00:00:00-07', '2022-07-20 00:00:00-07', N'A'),
(10, 50, '2022-07-01 00:00:00-07', '2022-07-10 00:00:00-07', N'C'),
(2, 10000, '2022-07-05 00:00:00-07', '2022-07-31 00:00:00-07', N'C');


--10, 1
INSERT INTO LOAI_HANG (TEN_LH) 
VALUES 
(N'Thức ăn'),
(N'Mỹ phẩm và làm đẹp'),
(N'Thời trang'),
(N'Đồ chơi'),
(N'Y tế'),
(N'Chuồng thú');

--200000, 1
INSERT INTO SAN_PHAM (MALH, MANPP, TEN_SP, HINH_ANH, MO_TA, CONG_KENH, GIA_BAN) 
VALUES 
(10, 1000, N'Thức ăn cho chó Poodle con ROYAL CANIN Poodle Puppy', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065285/food/thuc-an-cho-cho-poodle-con-royal-canin-poodle-puppy1_j0i9m3.webp', N'Thức ăn cho chó Poodle  con ROYAL CANIN  Poodle Puppy dành riêng cho tất cả các giống chó Teacup, Tiny Poodle, Toy Poodle, Standard Poodle dưới 10 tháng tuổi', FALSE, 155000),
(10, 1000, N'Thức ăn cho chó con cỡ nhỏ ROYAL CANIN Mini Puppy', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065284/food/thuc-an-cho-cho-con-co-nho-royal-canin-mini-puppy1_lupyrd.webp', N'Thức ăn cho chó con cỡ nhỏ ROYAL CANIN Mini Puppy dành cho các giống chó con dưới 10 tháng tuổi. Với công thức đặc chế riêng cho nhu cầu dinh dưỡng của chó con thuộc các giống cỡ nhỏ. Thức ăn cho chó con (các giống chó cỡ nhỏ) được nghiên cứu để cung cấp dinh dưỡng theo nhu cầu thực tế của chó con. Duy trì sức đề kháng cho chó con: chất chống oxy hóa CELT. Hỗ trợ hệ tiêu hóa hoạt động ổn định: L.I.P, đường FOS. Cung cấp dinh dưỡng toàn diện cho chó: chế biến theo công thức cung cấp năng lượng cao', FALSE, 185000),
(10, 1000, N'Thức ăn cho mèo trưởng thành ROYAL CANIN Regular Fit 32', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065286/food/thuc-an-cho-meo-truong-thanh-royal-canin-regular-fit-321_pvctbz.webp', N'Thức ăn cho mèo  trưởng thành ROYAL CANIN  Regular Fit 32 dành cho tất cả các giống mèo trưởng thành từ 12 tháng tuổi trở lên. Sản phẩm giúp duy trì thể trạng khỏe mạnh cho mèo. Duy trì cân nặng ổn định. Đảm bảo hệ tiêu hóa cân bằng. Hỗ trợ hệ tiết niệu khỏe mạnh. Xenlulozơ: kích thích tiêu hóa, tăng khả năng hấp thu chất dinh dưỡng. Albumin: thành phần quan trọng nhất cấu tạo nên nhiều cơ quan trong cơ thể', FALSE, 95000),
(10, 1000, N'Thức ăn cho mèo trưởng thành ROYAL CANIN Indoor 27', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065285/food/thuc-an-cho-meo-truong-thanh-royal-canin-indoor-27_xx1kmt.webp', N'Thức ăn cho mèo  trưởng thành ROYAL CANIN  Indoor 27 dành cho tất cả giống mèo sống trong nhà trên 12 tháng (Royal Canin Adult 1 tuổi).', FALSE, 105000),
(10, 1000, N'Thức ăn cho chó trưởng thành cỡ vừa ROYAL CANIN Medium Adult', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065285/food/thuc-an-cho-cho-truong-thanh-royal-canin-medium-adult1_jouft7.webp', N'Thức ăn cho chó trưởng thành cỡ vừa ROYAL CANIN Medium Adult dành cho những chú chó trưởng thành 12 tháng tuổi trở lên. Với công thức đặc chế riêng cho nhu cầu dinh dưỡng của chó trưởng thành.', FALSE, 155000),
(10, 1001, N'Thức ăn cho mèo giúp loại bỏ búi lông ZENITH Cat Hairball', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065286/food/zenith-cat-hairball_rkcc6z.webp', N'Thức ăn cho mèo  giúp loại bỏ búi lông ZENITH  Cat Hairball được chế biến từ thịt cá hồi, thịt nạc gà rút xương, gạo lứt, yến mạch và bột rong biển giúp đào thải búi lông. Với các thành phần tươi sạch, giàu dinh dưỡng. Thức ăn cho mèo giúp loại bỏ búi lông ZENITH Cat Hairball hạt mềm, cung cấp độ ẩm cao và lượng muối thấp, thơm ngon, dễ nhai, dễ tiêu hóa và tốt cho sức khỏe của mèo.', FALSE, 230000),
(10, 1000, N'Thức ăn cho mèo dưỡng đẹp lông ROYAL CANIN Hair & Skin', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065285/food/thuc-an-cho-meo-duong-dep-long-royal-canin-hair-skin1_lqrbhs.webp', N'Thức ăn cho mèo  dưỡng đẹp lông ROYAL CANIN  Hair & Skin cho tất cả giống mèo trưởng thành từ 12 tháng tuổi trở lên. Sản phẩm được nghiên cứu dành riêng cho những giống mèo có lông dày. \nĐảm bảo cung cấp đủ dinh dưỡng theo nhu cầu thực tế của mèo. Albumin là thành phần quan trọng cấu tạo nên một số cơ quan trong cơ thể. Các axit béo thiết yếu cung cấp năng lượng, giúp lông khỏe và mượt. Khoáng chất giúp xương và da phát triển khỏe mạnh, ít bệnh.', FALSE, 110000),
(10, 1002, N'Thức ăn cho chó hạt mềm vị thịt bò ORIGI-7 Beef', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065285/food/thuc-an-cho-cho-hat-mem-vi-thit-bo-origi-7-beef_h9xknt.webp', N'Thức ăn cho chó hạt mềm vị thịt bò ORIGI-7  Beef được làm từ thịt bò tươi ngon, chỉ sử dụng nguồn nguyên liệu hữu cơ sạch, an toàn, cung cấp đầy đủ dinh dưỡng cho thú cưng phát triển khỏe mạnh.', FALSE, 250000),
(10, 1006, N'Pate cho chó hỗ trợ chức năng gan và sáng mắt IRIS Benefit For Eyes & Liver', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065287/food/pate-cho-cho-ho-tro-chuc-nang-gan-va-sang-mat-iris-benefit-for-eyes-liver_dls3ib.webp', N'Pate cho chó hỗ trợ chức năng gan và sáng mắt IRIS  Benefit For Eyes & Liver là sản phẩm dành cho tất cả giống chó. Với thành phần hoàn toàn từ tự nhiên', FALSE, 35000),
(10, 1006, N'Pate cho chó vị bò và rau IRIS HRBV375 Beef Vegetable', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065287/food/pate-cho-cho-vi-bo-va-rau-iris-hrbv375-beef-vegetable3_jpqe56.webp', N'Pate cho chó vị bò và rau IRIS  HRBV375 Beef Vegetable dành cho tất cả các giống chó. Bảo quản sản phẩm nơi khô ráo và thoáng mát. Thời hạn sử dụng 24 tháng kể từ ngày sản xuất', FALSE, 85000),
(10, 1006, N'Pate cho chó giảm rụng lông IRIS Benefit For Fur', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065286/food/pate-cho-cho-giam-rung-long-iris-benefit-for-fur_x1lpjv.webp', N'Pate cho chó giảm rụng lông IRIS  Benefit For Fur là sản phẩm dành cho tất cả giống chó. Với thành phần hoàn toàn từ tự nhiên', FALSE, 35000),
(10, 1003, N'Súp thưởng cho chó thơm miệng INABA WANG Oral Health', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065287/food/sup-thuong-cho-cho-thom-mieng-inaba-wang-oral-health_cdl7n2.webp', N'Súp thưởng cho chó chắc xương INABA  WANG Joint Health với thành phần Polyphenol trong trà xanh gấp 5 lần sẽ giúp cho răng miệng của chó luôn sạch sẽ, ngăn ngừa sâu răng và hôi miệng.. Sản phẩm không chứa chất bảo quản. Chó đặc biệt rất thích loại nước súp thưởng này', FALSE, 40000),
(10, 1003, N'Súp ăn liền cho chó vị gà và phô mai INABA WANG Chicken & Cheese', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065286/food/sup-an-lien-cho-cho-vi-ga-va-pho-mai-inaba-wang-chicken-cheese_uhppiz.webp', N'Súp ăn liền cho chó vị gà và khoai tây INABA  WANG Chicken & Potatoes với thành phần hương vị hỗn hợp chất lượng cao đã được say nhuyễn. Có thể thưởng cho chó ăn vặt trực tiếp hoặc trộn cùng với thức ăn khác. Sản phẩm không chứa chất bảo quản. Chó đặc biệt rất thích loại nước súp thưởng này', FALSE, 40000),
(10, 1004, N'Bánh thưởng cho chó vị thịt bò VEGEBRAND Orgo Freshening Biscuit Bacon Beef', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065287/food/banh-thuong-cho-cho-vi-thit-bo-vegebrand-orgo-freshening-biscuit-bacon-beef_kbigw2.webp', N'Bánh thưởng cho chó vị thịt bò VEGEBRAND  Orgo Freshening Biscuit Bacon Beef có tác dụng làm sạch răng cho chó vị thịt bò. Sản phẩm có chứa các thành phần bạc hà tự nhiên kết hợp với hương vị thịt bò, có khả năng loại bỏ các vi khuẩn gây hôi miệng cho chú chó của bạn một cách nhanh chóng. Sản phẩm có thể kết hợp dùng để huấn luyện', FALSE, 25000),
(10, 1004, N'Xương gặm sạch răng cho chó VEGEBRAND Orgo Freshening Peppermint', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065287/food/pate-cho-meo-huong-vi-ca-ngu-va-cua-iris-tuna-crab_jk30fu.webp', N'Xương gặm sạch răng cho chó VEGEBRAND  Orgo Freshening Peppermint là sản phẩm dinh dưỡng dành cho chó trên 5 tháng tuổi', FALSE, 100000),
(10, 1005, N'Pate cho mèo vị nước sốt thịt bò WHISKAS Beef Flavour Sauce', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065289/food/pate-cho-meo-vi-nuoc-sot-thit-bo-whiskas-beef-flavour-sauce_rfdzzi.webp', N'Pate cho mèo vị nước sốt thịt bò WHISKAS  Beef Flavour Sauce, thơm ngon đặc trưng dành riêng cho mèo, giúp mèo cưng ăn uống ngon miệng hơn. Tăng miễn dịch, hỗ trợ tiêu hóa. Chăm sóc lông mềm mượt và hạn chế tối đa tỷ lệ rụng lông hàng năm của mèo cưng', FALSE, 25000),
(10, 1006, N'Pate cho mèo hương vị cá ngừ và cua IRIS Tuna & Crab', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065287/food/pate-cho-meo-huong-vi-ca-ngu-va-cua-iris-tuna-crab_jk30fu.webp', N'Pate cho mèo hương vị cá ngừ và cua IRIS  Tuna & Crab là thức ăn dành riêng cho tất cả giống mèo', FALSE, 35000),
(10, 1007, N'Súp thưởng cho mèo CIAO Tuna vị cá ngừ biển', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065286/food/sup-thuong-cho-meo-ciao-tuna-vi-ca-ngu-400x400_bggtmk.webp', N'Súp thưởng cho mèo  CIAO  Tuna vị cá ngừ biển say nhuyễn kết hợp với Polydextrose và Fructooligosaccharides có lợi cho tiêu hóa và sự hấp thụ dinh dưỡng của mèo. Có thể thưởng cho mèo ăn trực tiếp hoặc trộn cùng với thức ăn khác. Sản phẩm không chưa chất bảo quản. Mèo đặc biệt rất thích loại nước súp thưởng này', FALSE, 40000),
(10, 1007, N'Súp thưởng cho mèo vị cá ngừ cá chép CIAO Tuna & Bonito', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065284/food/sup-thuong-cho-meo-vi-ca-ngu-ca-chep-ciao-tuna-bonito_h9a9du.webp', N'Súp thưởng cho mèo  vị cá ngừ cá chép CIAO  Tuna & Bonito đã được say nhuyễn với hương vị thơm ngon. Soup thưởng CIAO Churu cũng giống như nước sốt pate cho mèo  có thể cho ăn trực tiếp, hoặc trộn cùng với thức ăn để giúp kích thích vị giác của mèo', FALSE, 175000),
(10, 1008, N'Bánh thưởng cho mèo vị cá hồi JERHIGH Jinny Salmon', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656065286/food/banh-thuong-cho-meo-vi-ca-hoi-jerhigh-jinny-salmon-flavored-400x400_rvsuop.webp', N'Bánh thưởng cho mèo  vị cá hồi JERHIGH  Jinny Salmon là thức ăn phụ và cũng để thưởng cho mèo. Cung cấp năng lượng cho chú mèo của bạn. Đây cũng được coi là thức ăn phụ và để thưởng cho người bạn bốn chân của bạn', FALSE, 45000),

(15, 1006, N'Nhà cho chó bằng nhựa IRIS Bob House', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656064414/house/nha-nhua-cho-cho-co-be-iris-09121_k7woru.webp', N'Nhà cho chó bằng nhựa IRIS  cỡ bé phù hợp với tất cả giống chó.', TRUE, 175000),
(15, 1009, N'Nhà cho chó mèo hình động vật PETISMILE', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656064414/house/nha-cho-meo-hinh-dong-vat-petismile_mnyq1v.webp', N'Nhà cho chó mèo hình động vật PETISMILE  là sản phẩm được dùng cho tất cả giống mèo', TRUE, 985000),
(15, 1006, N'Chuồng nhựa cho chó mèo IRIS 660', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656064416/house/chuong-nhua-cho-meo-iris-660_l2vhah.webp', N'Chuồng nhựa cho chó mèo IRIS 660 là sản phẩm giúp cho thú cưng của bạn cảm thấy thoải mái nhất khi ở trong. Chất liệu làm bằng nhựa ABS với độ bền cao và dễ dàng làm sạch. Sản phẩm kết hợp bánh bi di động thay đổi vị trí dễ dàng hoặc bạn có thể chốt vị trí cố định nếu bạn không muốn di chuyển thường xuyên.', TRUE, 1550000),
(15, 1006, N'Quây cho chó bằng nhựa nan nhỏ AUPET Exercise Playpen', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656064415/house/quay-cho-cho-bang-nhua-nan-nho-aupet-exercise-playpen_wjyggb.webp', N'Quây cho chó bằng nhựa nan nhỏ AUPET Exercise Playpen được sản xuất bởi chất liệu nhựa cao cấp PP an toàn cho thú cưng, thân thiện với môi trường, không gây độc hại.', TRUE, 1550000),
(15, 1006, N'Quây cho chó bằng nhựa nan nhỏ AUPET Exercise Playpen', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656064415/house/quay-cho-cho-bang-nhua-nan-nho-aupet-exercise-playpen_wjyggb.webp', N'Quây cho chó bằng nhựa nan nhỏ AUPET Exercise Playpen được sản xuất bởi chất liệu nhựa cao cấp PP an toàn cho thú cưng, thân thiện với môi trường, không gây độc hại.', TRUE, 1550000),
(15, 1010, N'Đệm cho chó mèo thành cao BOBBY PET 16OB002', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656064417/house/dem-cho-cho-meo-thanh-cao-bobby-pet-16ob002_htochu.webp', N'Đệm cho chó mèo thành cao BOBBY PET 16OB002 được thiết kế dành riêng cho vật nuôi. Phù hợp với tất cả các giống chó mèo.', TRUE, 455000),
(15, 1010, N'Nệm cho chó mèo BOBBY PET DS14OB', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656064414/house/nem-cho-cho-meo-bobby-pet-ds14ob_grmodi.jpg', N'Nệm cho chó mèo BOBBY PET DS14OB được thiết kế dành riêng cho vật nuôi. Bao gồm lớp vải mỏng bên ngoài, bên trong được cấu tạo bởi một lớp lông cừu dày và ấm áp. Chất liệu bền và dễ dàng vệ sinh sạch sẽ. Ổ đệm hình tròn có thành cao tạo cảm giác thoải mái nhất cho thú cưng khi nằm. Phần đệm dưới tạo cảm giác êm ái nằm. Cún cưng sẽ ngủ ngon giấc hơn. Là một chiếc giường lý tưởng để nghỉ ngơi sau khi vui chơi và huấn luyện. Bạn cũng có thể dễ dàng giặt sạch ổ nệm khi bị bẩn.', TRUE, 455000),
(15, 1011, N'Ổ đệm cho chó mèo PAW hình con cá mập', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656064414/house/o-dem-cho-cho-meo-paw-hinh-con-ca-map_izfkn9.jpg', N'Ổ đệm cho chó mèo PAW hình con cá mập với chất liệu vải nhung mềm mại, cao cấp an toàn cho thú cưng. Cho thú cưng một cảm giác êm ái khi nằm trên nệm. Với sắc xanh nổi bật. Được thiết kế cách điệu vô cùng đáng yêu. Mang tới những phút giây thư giãn và nghỉ ngơi cho thú cưng của bạn. Ổ đệm được làm từ chất liệu vải cao cấp. Bao gồm lớp vải mỏng bên ngoài, bên trong là lớp lông cừu dày, êm. Đặc biệt rất dễ để vệ sinh và làm sạch khi bẩn. Phù hợp với không gian ngôi nhà của bạn. Bạn cũng có thể thoải mái di chuyển nệm tới bất kì vị trí nào mà bạn mong muốn.', TRUE, 580000),
(15, 1012, N'Nhà cây cho mèo Cat Tree QQ80349-3', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656064414/house/nha-cay-cho-meo-cat-tree-qq80349-3-400x401_ojvgvo.webp', N'Nhà cây cho mèo Cat Tree QQ80349-3 hay còn gọi là cat stand, cat condo. Có thể hiểu như một ngôi nhà, một sân chơi, một phòng tập thể hình dành cho mèo yêu tận hưởng những giây phút thư giãn, giải trí.', TRUE, 3500000),
(15, 1012, N'Trụ cào móng cho mèo kèm đồ chơi QQ60060B', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656064415/house/tru-cao-mong-cho-meo-kem-do-choi-qq60060b_ondygn.webp', N'Trụ cào móng cho mèo  kèm đồ chơi QQ60060B được ưa chuộng tại châu Âu và nhiều quốc gia trên thế giới. Chất liệu tự nhiên, bền tốt không bị trầy xước, giúp móng mèo luôn chắc khỏe, tránh thiệt hại các vật dụng trong nhà.', TRUE, 400000),
(15, 1013, N'Chuồng mèo 2 tầng nan sắt AUPET 2-Layer Cat Cage', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656064416/house/chuong-meo-2-tang-nan-sat-aupet-2-layer-cat-cage5_snuy1c.webp', N'Chuồng mèo với thiết kế sang trọng có kết cấu chắc chắn đảm bảo an toàn cho thú cưng. Với lớp sơn sắt trắng bóng cao cấp chống gỉ giúp tăng độ bền và dễ dàng khi vệ sinh. Cửa trước có thể đảo ngược, giúp kiểm soát an toàn, cho mèo dễ dàng ra vào cũng như định vị một cách linh hoạt. Võng phía trên giúp mèo nghỉ ngơi và thư giãn. Chuồng mèo 2 tầng nan sắt AUPET 2-Layer Cat Cage có 5 bánh xe, 4 bánh 4 góc và 1 bánh ở giữa dễ dàng di chuyển theo ý muốn.', TRUE, 2800000),
(15, 1012, N'Nhà cây cho mèo Cat Tree QQ80862', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656064414/house/nha-cay-cho-meo-cat-tree-qq80862_k5frpx.webp', N'Nhà cây cho mèo Cat Tree QQ80862 đơn giản mà tinh tế với chân đế vững chắc. Phù hợp với tất cả các giống mèo ở các lứa tuổi khác nhau. Sản phẩm có thể tháo lắp để vệ sinh dễ dàng, tiện lợi.', TRUE, 1800000),
(15, 1014, N'Nhà nhựa cho chó có cửa sổ trời XINDING 419A', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656064414/house/nha-cho-cho-bang-nhua-dang-cao-xinding-419a-2_v4id4b.webp', N'Nhà nhựa cho chó có cửa sổ trời XINDING  419A là sản phẩm dành cho tất cả giống chó.', TRUE, 3080000),
(15, 1010, N'Ổ đệm cho chó mèo hình lều BOBBY PET 16CT001', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656064415/house/o-dem-cho-cho-meo-hinh-leu-bobby-pet-16ct001_nxcqao.webp', N'Ổ đệm cho chó mèo hình lều BOBBY PET 16CT001 được thiết kế dành riêng cho vật nuôi. Phù hợp với tất cả các giống chó mèo.', TRUE, 495000),
(15, 1015, N'Ổ đệm cho chó mèo vải họa tiết động vật ELITE', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656064415/house/o-dem-cho-cho-meo-vai-hoa-tiet-dong-vat-elite_wpuhjf.webp', N'Ổ đệm cho chó mèo vải họa tiết động vật ELITE  với thiết kế hình nôi độc đáo và ấm áp. Phù hợp với tất cả các giống chó mèo khác nhau.', TRUE, 395000),
(15, 1010, N'Thảm cho chó mèo nằm loại dày BOBBY PET DS14RC', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656064415/house/tham-cho-cho-meo-nam-loai-day-bobby-pet-ds14rc_grgnc7.jpg', N'Thảm cho chó mèo nằm loại dày BOBBY PET DS14RC được thiết kế dành riêng cho vật nuôi nằm. Bao gồm lớp vải mỏng bên ngoài, bên trong được cấu tạo bởi một lớp lông cừu dày & ấm áp, chất liệu bền và dễ dàng vệ sinh sạch sẽ. Thảm nằm hình chữ nhật giúp cún cưng có thể nằm thoải mái với đủ các tư thế nằm khác nhau. Một chiếc giường êm ái sẽ giúp thú cưng thư giãn sau khi vận động và tham gia huấn luyện. Có thể vệ sinh dễ dàng khi bẩn.', TRUE, 655000),

(12, 1017, N'Quần áo cho chó mèo AMBABY PET 2JXF216', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656066666/fashion/quan-ao-cho-cho-meo-ambaby-pet-2jxf216_kkudai.webp', N'Sản phẩm được thiết kế với chất liệu cotton và gia công tỉ mỉ, Kiểu dáng dễ mặc, dễ vận động đem đến sự thoải mái cho chó mèo', FALSE, 180000),
(12, 1017, N'Quần áo cho chó mèo AMBABY PET 2JXF164', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656066666/fashion/quan-ao-cho-cho-meo-ambaby-pet-2jxf164_gtegje.webp', N'Sản phẩm được thiết kế với chất liệu cotton và gia công tỉ mỉ, Kiểu dáng dễ mặc, dễ vận động đem đến sự thoải mái cho chó mèo', FALSE, 245000),
(12, 1017, N'Yếm cho chó mèo kèm dây dắt AMBABY PET 1JXS058', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656066665/fashion/yem-cho-cho-meo-kem-day-dat-ambaby-pet-1jxs058-400x400_f1xuav.webp', N'Chất liệu vải cao cấp tuyệt đối không ảnh hưởng đến sức khỏe của chó mèo, Thú cưng của bạn sẽ được chú ý, thu hút từ ánh mắt của mọi người', FALSE, 255000),
(12, 1017, N'Vòng cổ cho chó mèo kèm dây dắt AMBABY PET 1JXS041', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656066665/fashion/vong-co-cho-cho-meo-kem-day-dat-ambaby-pet-1jxs041-400x400_iz8vcp.webp', N'Vòng cổ cho chó mèo kèm dây dắt AMBABY PET  1JXS041 là sản phẩm dùng cho tất cả giống chó và mèo theo từng kích cỡ phù hợp.', FALSE, 225000),
(12, 1017, N'Yếm cho chó mèo kèm dây dắt AMBABY PET 1JXS015', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656066665/fashion/yem-cho-cho-meo-kem-day-dat-ambaby-pet-1jxs015-400x400_chvxaq.webp', N'Yếm cho chó mèo kèm dây dắt AMBABY PET  1JXS015 là sản phẩm dành cho tất cả giống chó và mèo', FALSE, 255000),
(12, 1016, N'Dây dắt chó mèo đi dạo tự cuốn DELE 009 Retractable Leash', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656066666/fashion/dat-cho-meo-di-dao-tu-cuon-dele-009-retractable-leash_ygyt39.webp', N'Dây dắt chó mèo đi dạo tự cuốn DELE  009 Retractable Leash là sản phẩm phù hợp cho những giống chó dưới 40kg.', FALSE, 175000),
(12, 1011, N'Vòng cổ cho chó cỡ nhỏ PAW bằng da đính cườm cao cấp', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656066665/fashion/vong-co-cho-cho-co-nho-paw-bang-da-dinh-cuom-cao-cap_wizvbg.jpg', N'Vòng cổ cho chó cỡ nhỏ PAW  bằng da đính cườm cao cấp là sản phẩm dành cho tất cả giống chó cỡ nhỏ.', FALSE, 170000),
(12, 1017, N'Quần áo cho chó mèo AMBABY PET 2JXF112', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656066666/fashion/quan-ao-cho-cho-meo-ambaby-pet-2jxf112-400x400_uco26a.webp', N'Sản phẩm được thiết kế với chất liệu cotton và gia công tỉ mỉ, Kiểu dáng dễ mặc, dễ vận động đem đến sự thoải mái cho chó mèo', FALSE, 245000),
(12, 1018, N'Túi đựng chó mèo ANIME hình họa tiết White Cats', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656066666/fashion/tui-dung-cho-meo-anime-hinh-hoa-tiet-white-cats_opl5r7.webp', N'Chất liệu túi không thấm nước và dễ làm vệ sinh làm sạch. Dễ dàng tháo gấp gọn lại khi cần', FALSE, 300000),
(12, 1009, N'Balo đựng chó mèo PETISMILE Dis78 Favorite Space', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656066666/fashion/balo-dung-cho-meo-petismile-dis78-favorite-space-400x401_ewacp7.webp', N'Chất liệu túi không thấm nước và dễ làm vệ sinh làm sạch. Dễ dàng tháo gấp gọn lại khi cần', FALSE, 995000),
(12, 1018, N'Túi đựng chó mèo ANIME nhựa trong', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656066666/fashion/tui-dung-cho-meo-anime-nhua-trong-400x400_wgxyvw.webp', N'Chất liệu túi không thấm nước và dễ làm vệ sinh làm sạch. Dễ dàng tháo gấp gọn lại khi cần', FALSE, 300000),
(12, 1019, N'Balo đựng chó mèo phi hành gia LOFFE Panoramic', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656066666/fashion/balo-dung-cho-meo-phi-hanh-gia-loffe-panoramic-400x400_te3idw.webp', N'Sản phẩm được tích hợp dây xích an toàn, tấm lưới lỗ thông gió, lót mềm mại tạo cho thú cưng cảm giác thoải mái, tiện lợi và an toàn.', FALSE, 525000),
(12, 1011, N'Rọ mõm cho chó mõm ngắn PAW', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656066666/fashion/ro-mom-cho-cho-mom-ngan-paw-nhieu-kich-co_p48m4a.jpg', N'Rọ mõm cho chó mõm ngắn PAW  nhiều kích cỡ phù hợp cho các giống chó: Pug, Bull Pháp, Bull Anh, Boxer, Bắc Kinh, Nhật…', FALSE, 230000),
(12, 1011, N'Vòng cổ chống liếm cho chó mèo PAW Pet Elizabethan Collar', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656066945/fashion/vong-co-chong-liem-cho-cho-meo-paw-pet-elizabethan-collar-400x400_erefyg.webp', N'Vòng cổ chống liếm cho chó mèo PAW Pet Elizabethan Collar hay còn gọi là vòng xấu hổ với chất liệu nhựa mềm nhập khẩu, an toàn, kiên cố, thiết kế hiện đại không gây tổn thương cho cơ thể của thú cưng. Tác dụng chính của sản phẩm: Chống thú cưng liếm vào cơ thể khi bôi thuốc và dễ dàng tắm, cắt tỉa lông và làm đẹp cho thú cưng. Sản phẩm dùng được cho tất cả các giống chó mèo. Lưu ý khi lựa chọn size phù hợp cho thú cưng: Bạn cần phải đo đúng kích thước vòng cổ của thú cưng, sau đó đo độ dài từ cổ đến miệng đồng thời kiểm tra kích thước chiều sâu.  Kích thước của các số từ 1 đến 7 chỉ là để tham khảo, vui lòng xem và thử trực tiếp tại cửa hàng.', FALSE, 50000),
(12, 1021, N'Địu chó mèo AUGUST PET P68027B', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656066665/fashion/diu-cho-meo-august-pet-p68027b-400x400_vuypul.webp', N'Địu chó mèo AUGUST PET P68027B được làm từ chất liệu vải cao cấp cực kì chắc chắn. Được dùng cho tất cả giống chó và mèo.', FALSE, 250000),

(13, 1015, N'Đồ chơi cho chó kêu chút chít bằng cao su ELITE hình thú', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656067857/toys/do-choi-cho-cho-keu-chut-chit-bang-cao-su-elite-hinh-thu_gnb8ve.webp', N'Sản phẩm có kích thước nhỏ gọn, màu sắc như thật, âm thanh chút chít đáng yêu sẽ khiến cho cún cưng không cảm thấy cô đơn khi ở nhà một mình.', FALSE, 50000),
(13, 1015, N'Đồ chơi cho chó kêu chút chít bằng cao su ELITE hình con hươu', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656067857/toys/do-choi-cho-cho-keu-chut-chit-bang-cao-su-elite-hinh-con-huou_k67gpp.webp', N'Đồ chơi cho chó kêu chút chít bằng cao su ELITE hình con hươu ngăn ngừa thói quen cắn phá của cún con. Tránh chó cưng sủa, làm rách đồ đạc và chán ăn.', FALSE, 50000),
(13, 1015, N'Đồ chơi cho chó mèo kêu chút chít ELITE hình thú bông', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656067857/toys/do-choi-cho-cho-meo-keu-chut-chit-elite-hinh-thu-bong-400x400_s8b79n.webp', N'Là món đồ giúp thú cưng ở trong nhà mà không cảm thấy nhàm chán khi bị bỏ lại một mình. Món đồ chơi đặc biệt dễ thương này không chỉ giúp chú chó giải trí mà còn bảo vệ những thứ quan trọng cho bạn như giày dép, bàn ghế, tủ…', FALSE, 105000),
(13, 1015, N'Đồ chơi cho chó kêu chút chít ELITE hình thú ôm dây thừng', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656067857/toys/do-choi-cho-cho-keu-chut-chit-elite-hinh-thu-om-day-thung_kdbpx9.webp', N'Thiết kế âm thanh, thiết bị âm thanh tích hợp, đồ chơi sẽ phát ra âm thanh khi chơi, tăng thêm niềm vui cho cún cưng.', FALSE, 50000),
(13, 1011, N'Đồ chơi dây thừng cho chó mèo PAW loại dài', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656067858/toys/do-choi-day-thung-cho-cho-meo-paw-loai-dai_azeg26.webp', N'Sản phẩm giúp hạn chế nhu cầu gặm phá đồ đạc của thú cưng trong gia đình.', FALSE, 50000),
(13, 1011, N'Đồ chơi cần câu cho mèo PAW vui nhộn', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656067858/toys/do-choi-can-cau-cho-meo-paw_thxqki.webp', N'Đồ chơi cần câu cho mèo PAW có thể hỗ trợ chú mèo tích cực tập thể dục mỗi ngày, không chỉ tăng cường mối quan hệ với chủ nhân mà còn duy trì một cơ thể hoàn hảo, tránh việc thiếu vận động trong nhà dẫn đến béo phì. Ưu điểm của cần câu mèo này là dây thép dẻo dai, siêu bền, bạn có thể lắc đi lắc lại, như một con cim lông vũ bay trên trời, sẽ gợi nhớ đến ký ức đuổi bắt các loại chim trong thế giới tự nhiên, khiến mèo cảm thấy vui vẻ.', FALSE, 75000),
(13, 1015, N'Đồ chơi cho chó mèo bằng bông chút chít ELITE hình tuần lộc', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656067858/toys/do-choi-cho-cho-meo-bang-bong-chut-chit-elite-hinh-tuan-loc-400x400_rtcyxs.webp', N'Là món đồ giúp thú cưng ở trong nhà mà không cảm thấy nhàm chán khi bị bỏ lại một mình. Món đồ chơi đặc biệt dễ thương này không chỉ giúp chú chó giải trí mà còn bảo vệ những thứ quan trọng cho bạn như giày dép, bàn ghế, tủ…', FALSE, 135000),
(13, 1011, N'Đồ chơi mèo bằng cói PAW hình cá size XL', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656067858/toys/do-choi-meo-bang-coi-paw-hinh-ca-size-xl_tiirwv.webp', N'Đồ chơi mèo bằng cói PAW hình cá size XL với chất liệu bằng cói tự nhiên rất an toàn và không gây độc hại. Không những chỉ có tính năng làm đồ chơi, sản phẩm còn giúp mèo của bạn trở nên hoạt bát hơn, năng động hơn. Đồng thời còn có tác dụng để kích thích và định hướng mèo cào mài móng của mình, tránh làm hỏng hóc các đồ vật trong nhà. Đặc biệt nó còn gây tiếng động có tác dụng kích thích sự tò mò tự nhiên của mèo, giúp phát triển toàn diện hơn.', FALSE, 150000),
(13, 1011, N'Đồ chơi cho chó bằng cao su hình xương PAW', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656067858/toys/do-choi-cho-cho-bang-cao-su-soleil-co-gai-hinh-ban-chan_efxebz.webp', N'Sản phẩm đồ chơi cho chó được thiết kế với nhiều hình dáng khác nhau và đặc biệt được thiết kế với chức năng làm sạch răng cho chó khi chúng gặm, cắn sản phẩm.', FALSE, 75000),
(13, 1011, N'Đồ chơi cho chó bằng cao su PAW có gai hình bàn chân', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656067858/toys/do-choi-cho-cho-hinh-xuong-cao-su-soleil-rubber-dog-toy-small-solid-bone_hciuhm.webp', N'Đồ chơi cho chó với chất liều bằng cao su cao cấp tự nhiên, không gây độc hại cho chó. Có độ bền cao và khả năng đàn hồi tốt.', FALSE, 55000),
(13, 1022, N'Đồ chơi cho mèo BOBO BO4804', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656067857/toys/do-choi-cho-meo-bobo-bo4804_rq79jb.webp', N'Đồ chơi cho mèo BOBO BO4804 với chất liệu bằng cói tự nhiên rất an toàn và không gây độc hại. Không những chỉ có tính năng làm đồ chơi, sản phẩm còn giúp mèo của bạn trở nên hoạt bát hơn, năng động hơn. Đồng thời còn có tác dụng để kích thích và định hướng mèo cào mài móng của mình, tránh làm hỏng hóc các đồ vật trong nhà. Đặc biệt nó còn gây tiếng động có tác dụng kích thích sự tò mò tự nhiên của mèo, giúp phát triển toàn diện hơn.', FALSE, 110000),
(13, 1022, N'Đồ chơi dây thừng cho chó mèo đan chéo BOBO', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656067857/toys/do-choi-day-thung-cho-cho-meo-dan-cheo-bobo-1033_hivwwz.jpg', N'Sản phẩm giúp hạn chế nhu cầu gặm phá đồ đạc của thú cưng trong gia đình, khiến chúng thích thú và đùa nghịch suốt cả ngày.', FALSE, 55000),
(13, 1022, N'Đồ chơi cho mèo bằng cói BOBO hình cá', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656067857/toys/do-choi-cho-meo-bang-coi-bobo-hinh-ca_mrnkgj.jpg', N'Đồ chơi cho mèo bằng cói BOBO hình cá với chất liệu bằng cói tự nhiên rất an toàn và không gây độc hại. Không những chỉ có tính năng làm đồ chơi, sản phẩm còn giúp mèo của bạn trở nên hoạt bát hơn, năng động hơn. Đồng thời còn có tác dụng để kích thích và định hướng mèo cào mài móng của mình, tránh làm hỏng hóc các đồ vật trong nhà. Đặc biệt nó còn gây tiếng động có tác dụng kích thích sự tò mò tự nhiên của mèo, giúp phát triển toàn diện hơn.', FALSE, 85000),
(13, 1022, N'Đồ chơi cho mèo bằng cói BOBO ống thừng 3 bóng', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656067857/toys/do-choi-cho-meo-bang-coi-bobo-ong-thung-3-bong_owkr8t.jpg', N'Đồ chơi cho mèo bằng cói BOBO ống thừng 3 bóng với chất liệu bằng cói tự nhiên rất an toàn và không gây độc hại. Không những chỉ có tính năng làm đồ chơi, sản phẩm còn giúp mèo của bạn trở nên hoạt bát hơn, năng động hơn. Đồng thời còn có tác dụng để kích thích và định hướng mèo cào mài móng của mình, tránh làm hỏng hóc các đồ vật trong nhà. Đặc biệt nó còn gây tiếng động có tác dụng kích thích sự tò mò tự nhiên của mèo, giúp phát triển toàn diện hơn.', FALSE, 110000),
(13, 1022, N'Đồ chơi dây thừng cho chó mèo BOBO hình chó', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656067857/toys/do-choi-day-thung-cho-cho-meo-bobo-hinh-cho_hmfafh.webp', N'Sản phẩm giúp hạn chế nhu cầu gặm phá đồ đạc của thú cưng trong gia đình.', FALSE, 55000),

(11, 1011, N'Kềm cắt bấm móng chó mèo PAW Pet Nail Clipper', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656069259/cares/kem-cat-bam-mong-cho-meo-paw-pet-nail-clipper_fr7dlq.webp', N'Kềm cắt bấm móng chó mèo PAW Pet Nail Clipper làm bằng vật liệu hợp kim chất lượng cao, bền, lưỡi kìm sắc nhọn. Hoạt động theo thiết kế vòng cung động cơ đẩy, dễ dàng sử dụng.', FALSE, 70000),
(11, 1023, N'Máy mài móng chó mèo JOYU Pet Nail Grinder N9', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656069260/cares/may-mai-mong-cho-meo-joyu-pet-nail-grinder-n91_epunmh.webp', N'JOYU Pet Nail Grinder N9 thiết kế tiện dụng, bạn có thể cảm thấy tay cầm rất thoải mái và máy dễ vận hành. Bạn có thể dễ dàng mài móng chó mèo của bạn ở nhà. Có 3 chức năng mài móng theo tốc độ: nhỏ, trung bình-lớn và nhanh. Mài móng cho chó mèo được hoạt động rất hiệu quả. Không gây đau, cắt tỉa, tạo hình theo yêu cầu và làm mịn móng cho thú cưng đáng yêu của bạn.', FALSE, 520000),
(11, 1016, N'Kềm cắt bấm móng chó mèo DELE Q022 Pet Nail Clipper', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656069262/cares/kem-bam-mong-cho-meo-dele-q022-pet-nail-clipper_y76uqb.webp', N'Kềm cắt bấm móng chó mèo DELE Q022 Pet Nail Clipper nhằm giúp cho vật nuôi được vệ sinh sạch sẽ móng vuốt. Tránh cào xước hay làm hư hại đến đồ dùng trong nhà. Sản phẩm được thiết kế chất lượng với tay cầm bằng nhựa PP, chắc chắn. Lò xo giữa kìm, tăng độ đàn hồi tránh việc cắt vào da thịt của chó mèo', FALSE, 195000),
(11, 1016, N'Lược chải lông chó mèo bấm nút DELE M006 Round Head', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656069260/cares/luoc-chai-long-cho-meo-bam-nut-dele-m006-round-head-400x400_zcudhs.webp', N'Lược chải lông chó mèo bấm nút DELE  M006 Round Head phù hợp với tất cả các giống chó. Bao gồm cả các giống chó nhỏ và chó lớn như Poodle, Phốc sóc, Samoyel, Alaska…', FALSE, 140000),
(11, 1022, N'Lược chải lông chó mèo đầu lưỡi mềm BOBO Pet Comb', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656069260/cares/luoc-chai-long-cho-meo-dau-luoi-mem-bobo-pet-comb7_hmck5i.webp', N'Lược chải lông chó mèo đầu lưỡi mềm BOBO  Pet Comb sử dụng cho tất cả các giống cho mèo lông thẳng và lông xoăn.', FALSE, 85000),
(11, 1024, N'Sữa tắm khô cho chó mèo JOYCE & DOLLS Waterless Cleansing Foam', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656069260/cares/Sua-tam-kho-cho-cho-meo-Joyce-Dolls-Waterless-Cleansing-Foam0_fjpdkr.webp', N'Sữa tắm khô cho chó mèo JOYCE & DOLLS Waterless Cleansing Foam phù hợp đặc biệt là trong trường hợp đang bị bệnh, đang mang thai. Hoặc trong nhiều trường hợp khác không thể tắm rửa bằng nước. Sản phẩm này có thể thay thế cho việc tắm bằng nước thông thường, làm sạch bụi bẩn và mùi hôi mọi lúc mọi nơi. Phù hợp với tất cả các giống chó mèo.', FALSE, 180000),
(11, 1024, N'Sữa tắm cho chó mèo hương hoa hồng JOYCE & DOLLS Rose Dew', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656069260/cares/sua-tam-cho-cho-meo-huong-hoa-hong-joyce-dolls-rose-dew-0_fjyeu5.webp', N'Sữa tắm cho chó mèo hương hoa hồng JOYCE DOLLS  Rose Dew là sữa tắm cho chó mèo với tinh dầu chiết xuất từ hoa hồng. Dành cho tất cả các giống chó mèo như Poodle, Phốc sóc, Samoyed, Alaska, mèo Anh lông dài, lông ngắn…', FALSE, 250000),
(11, 1024, N'Dầu xả cho chó mèo dưỡng lông JOYCE & DOLLS Dog Coat Finishing Conditioner', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656069260/cares/dau-xa-cho-cho-meo-duong-long-joyce-dolls-dog-coat-finishing-conditioner_ut0rl2.jpg', N'Dầu xả cho chó mèo dưỡng lông JOYCE DOLLS  Dog Coat Finishing Conditioner, dành có tất cả các giống chó. Bao gồm cả chó mèo lông ngắn và lông dài như Poodle, Phốc sóc, Phốc, Pug, Alaska…', FALSE, 180000),
(11, 1029, N'Tã bỉm cho chó mèo cái 2 – 4kg VET’S BEST Disposable Diapers XSmall', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656069260/cares/ta-bim-cho-cho-meo-cai-2-4kg-vets-best-disposable-diapers-xsmall-400x400_ewpcp2.webp', N'Tã bỉm cho chó mèo cái 2 – 4kg VETS BEST Disposable Diapers XSmall là giải pháp đơn giản và hiệu quả cho thú cưng của bạn bị tiểu tiện bừa bãi và khi chó cái đến giai đoạn đèn đỏ. Tã bỉm cho chó có kích thước vừa vặn với thú cưng 2 – 4kg. Sản phẩm có đường chỉ cho biết độ ẩm để bạn biết khi nào cần thay bỉm cho chó. Mỗi chiếc tã đều có một rào chắn hạn chế sự rò rỉ nước ra ngoài. An toàn lông và cố định vị trí cho chó dễ dàng đi vệ sinh mọi lúc mọi nơi. Kích thước: 22 – 40cm.', FALSE, 85000),
(11, 1025, N'Tã bỉm cho chó mèo cái PET SOFT Disposable Diapers XXSmall 1-3kg', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656069260/cares/ta-bim-cho-cho-meo-cai-pet-soft-disposable-diapers-large-10-20kg_svflai.webp', N'Tã bỉm cho chó mèo cái PET SOFT  Disposable Diapers XXSmall 1-3kg là giải pháp đơn giản và hiệu quả cho thú cưng của bạn bị tiểu tiện bừa bãi và khi chó cái đến giai đoạn đèn đỏ. Tã bỉm cho chó có kích thước vừa vặn với thú cưng 1 đến 3kg. Sản phẩm có đường chỉ cho biết độ ẩm để bạn biết khi nào cần thay bỉm cho chó. Mỗi chiếc tã đều có một rào chắn hạn chế sự rò rỉ nước ra ngoài. An toàn lông và cố định vị trí cho chó dễ dàng đi vệ sinh mọi lúc mọi nơi', FALSE, 10000),
(11, 1025, N'Tã bỉm cho chó mèo cái PET SOFT Disposable Diapers Large 10-20kg', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656069260/cares/ta-bim-cho-cho-meo-cai-pet-soft-disposable-diapers-large-10-20kg_svflai.webp', N'Tã bỉm cho chó mèo cái PET SOFT  Disposable Diapers Large 10-20kg là giải pháp đơn giản và hiệu quả cho thú cưng của bạn bị tiểu tiện bừa bãi và khi chó cái đến giai đoạn đèn đỏ. Tã bỉm cho chó có kích thước vừa vặn với thú cưng 10 đến 20kg. Sản phẩm có đường chỉ cho biết độ ẩm để bạn biết khi nào cần thay bỉm cho chó. Mỗi chiếc tã đều có một rào chắn hạn chế sự rò rỉ nước ra ngoài. An toàn lông và cố định vị trí cho chó dễ dàng đi vệ sinh mọi lúc mọi nơi.', FALSE, 20000),
(11, 1026, N'Cát vệ sinh thủy tinh cho mèo TRIXIE Silikatstreu', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656069260/cares/cat-ve-sinh-cho-meo-trixiesilikatstreu_c3dn91.webp', N'Cát vệ sinh thủy tinh cho mèo TRIXIE Silikatstreu là dạng hạt, có khả năng hấp thụ nước tiểu của mèo rất nhanh', FALSE, 160000),
(11, 1026, N'Bột khử mùi nước tiểu và phân mèo TRIXIE Katzen-Streudeo', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656069260/cares/bot-khu-mui-cat-ve-sinh-meo-trixie-katzen-streudeo-1_ao8ix8.webp', N'Bột khử mùi nước tiểu và phân mèo TRIXIE  Katzen-Streudeo được sử dụng để rắc phủ lên khu vực chậu cát vệ sinh của mèo, hỗ trợ giảm thiểu tối đa mùi hôi khó chịu từ nước tiểu và phân của mèo sau khi thải ra vào chậu cát vệ sinh.', FALSE, 150000),
(11, 1027, N'Thuốc tẩy giun cho chó BAYER Drontal Plus Flavour', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656069259/cares/thuoc-tay-giun-cho-cho-bayer-drontal-plus-flavour1_jptbmt.webp', N'Thuốc tẩy giun cho chó BAYER  Drontal Plus Flavour For Dogs điều trị đa nhiễm giun tròn, giun đũa, giun tóc, giun móc và sán dây. Giúp tẩy xổ tất cả những loài giun trưởng thành và ấu trùng nguy hiểm trên chó gây co cơ, liệt cơ làm giun không bám được vào vật chủ, còn Febantel cản trở giun sử dụng năng lượng cho các hoạt động làm giun chết nhanh. Giải quyết những vấn đề gây rối loạn tiêu hóa, bỏ ăn, có hiện tượng mệt mỏi do giun quấy', FALSE, 55000),
(11, 1027, N'Thuốc xổ giun cho mèo BAYER Drontal Cat', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656069259/cares/thuoc-xo-giun-cho-meo-bayer-drontal-cat_r37m4t.jpg', N'Thuốc xổ giun cho mèo BAYER  Drontal Cat sử dụng cho mèo con trên 6 tuần tuổi. Sử dụng 1 viên cho thể trọng 4kg. Có thể cho mèo ăn trực tiếp hoặc trộn lẫn vào thức ăn.', FALSE, 55000),
(11, 1028, N'Khay vệ sinh cho mèo MAKAR Cat Litter Station', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656069259/cares/thuoc-xo-giun-cho-meo-bayer-drontal-cat_r37m4t.jpg', N'Khay vệ sinh cho mèo  MAKAR  Cat Litter Station phù hợp cho mèo con và các giống mèo cỡ nhỏ. Màu sắc: nâu cà phê, xanh biển, hồng, trắng kem. Kích thước: 46 x 36,3 x 11cm. Với kích thước nhỏ gọn, không chiếm diện tích quá lớn. Sản phẩm có độ bền cao, hình thức đẹp, màu sắc đa dạng.', FALSE, 250000),
(11, 1006, N'Khay vệ sinh cho chó thành cao IRIS TRT500', 'https://res.cloudinary.com/ec-2022-lam-zau-khum-kho/image/upload/v1656069259/cares/ve-sinh-cho-cho-thanh-cao-iris-trt500-400x400_bnkzmc.webp', N'Khay vệ sinh cho chó thành cao IRIS  TRT500 với thiết kế hình vuông nhỏ gọn, thuận tiện cho việc cún cưng đi vệ sinh. Sử dụng chất liệu nhựa tổng hợp chất lượng cao. Có tính đàn hồi giúp chó mèo dẫm lên cảm thấy thoải mái. Phù hợp với tất cả các giống chó mèo, giới tính đực và cái.', FALSE, 395000);

-- 10000, 1
INSERT INTO PHIEU_NHAP_HANG (MANPP, MACN, NGAY_LAP, TONG_TIEN_NHAP, TONG_SO_MAT_HANG) 
VALUES 
(1000, 200, '2022-05-15 12:21:37', 1850000, 2),
(1002, 200, '2022-05-23 19:10:25', 2500000, 3),
(1003, 203, '2022-06-01 09:08:07', 1230000, 1),
(1004, 205, '2022-06-05 18:32:30', 4100000, 4),
(1005, 205, '2022-06-09 11:30:09', 4875000, 3),
(1006, 205, '2022-06-13 12:47:13', 1600000, 1),
(1007, 206, '2022-06-21 14:20:05', 1200000, 1),
(1008, 207, '2022-06-28 15:41:42', 6780000, 5),
(1009, 208, '2022-06-28 12:52:25', 5420000, 3),
(1010, 201, '2022-07-04 19:53:06', 3520000, 3);